### ISSUE TITLE
I need to obtain the encryption algorithm for FCM and obtain Authorization: AidLogin

### ISSUE THREAD

**Issue by a121418140** [bikram0000/flutter_fcm_decrypt#1]
I will give you corresponding job rewards. What contact information can I directly find you? I need your answer
![96f051b4-24ad-4870-9f97-cf015f362789](https://github.com/bikram0000/flutter_fcm_decrypt/assets/91479862/a09e4851-c850-4d85-8e2f-966d59d1c9b1)

**Comment by bikram0000** [comment]
I would be happy to help you. You can contact me through any of my social media accounts: https://github.com/bikram0000#-socials
